# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\资料\ultraquant_v6\ultraQuant_UI\Configuration\UI_mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(997, 741)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 5, 1, 1)
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_run.sizePolicy().hasHeightForWidth())
        self.btn_run.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_run.setFont(font)
        self.btn_run.setObjectName("btn_run")
        self.gridLayout_2.addWidget(self.btn_run, 0, 4, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 3, 1, 1)
        self.btn_import = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_import.sizePolicy().hasHeightForWidth())
        self.btn_import.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_import.setFont(font)
        self.btn_import.setObjectName("btn_import")
        self.gridLayout_2.addWidget(self.btn_import, 0, 0, 1, 1)
        self.btn_save_as = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save_as.sizePolicy().hasHeightForWidth())
        self.btn_save_as.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save_as.setFont(font)
        self.btn_save_as.setObjectName("btn_save_as")
        self.gridLayout_2.addWidget(self.btn_save_as, 0, 1, 1, 1)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_save.sizePolicy().hasHeightForWidth())
        self.btn_save.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_save.setFont(font)
        self.btn_save.setToolTip("")
        self.btn_save.setObjectName("btn_save")
        self.gridLayout_2.addWidget(self.btn_save, 0, 2, 1, 1)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.gridLayout_2)
        self.tab_box = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_box.sizePolicy().hasHeightForWidth())
        self.tab_box.setSizePolicy(sizePolicy)
        self.tab_box.setMinimumSize(QtCore.QSize(971, 591))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.tab_box.setFont(font)
        self.tab_box.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tab_box.setIconSize(QtCore.QSize(30, 30))
        self.tab_box.setObjectName("tab_box")
        self.tab_Quantitation = QtWidgets.QWidget()
        self.tab_Quantitation.setObjectName("tab_Quantitation")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_Quantitation)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.tab_Quantitation)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 928, 1207))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaWidgetContents.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.scrollAreaWidgetContents.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollAreaWidgetContents.setAutoFillBackground(True)
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_ini = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ini.sizePolicy().hasHeightForWidth())
        self.btn_ini.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_ini.setFont(font)
        self.btn_ini.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_ini.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.btn_ini.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_ini.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}\n"
"font: 75 10pt \"MS Shell Dlg 2\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("E:\\资料\\ultraquant_v6\\ultraQuant_UI\\Configuration\\Resource/icons/icon_show.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("E:\\资料\\ultraquant_v6\\ultraQuant_UI\\Configuration\\Resource/icons/icon_hide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_ini.setIcon(icon)
        self.btn_ini.setCheckable(True)
        self.btn_ini.setObjectName("btn_ini")
        self.verticalLayout_8.addWidget(self.btn_ini)
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.line_8 = QtWidgets.QFrame(self.frame)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 6, 0, 1, 1)
        self.lbl_ini_PA = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_ini_PA.setFont(font)
        self.lbl_ini_PA.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ini_PA.setObjectName("lbl_ini_PA")
        self.gridLayout.addWidget(self.lbl_ini_PA, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.line_22 = QtWidgets.QFrame(self.frame)
        self.line_22.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.gridLayout.addWidget(self.line_22, 0, 3, 1, 1)
        self.line_11 = QtWidgets.QFrame(self.frame)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.gridLayout.addWidget(self.line_11, 6, 4, 1, 1)
        self.line_24 = QtWidgets.QFrame(self.frame)
        self.line_24.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.gridLayout.addWidget(self.line_24, 2, 4, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 4, 1, 1)
        self.line_10 = QtWidgets.QFrame(self.frame)
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.gridLayout.addWidget(self.line_10, 6, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.frame)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout.addWidget(self.line_6, 2, 1, 1, 1)
        self.line_18 = QtWidgets.QFrame(self.frame)
        self.line_18.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.gridLayout.addWidget(self.line_18, 9, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.frame)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.ledt_ini_PG = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_ini_PG.setFont(font)
        self.ledt_ini_PG.setObjectName("ledt_ini_PG")
        self.horizontalLayout_6.addWidget(self.ledt_ini_PG)
        self.btn_ini_PG = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ini_PG.setFont(font)
        self.btn_ini_PG.setObjectName("btn_ini_PG")
        self.horizontalLayout_6.addWidget(self.btn_ini_PG)
        self.gridLayout.addLayout(self.horizontalLayout_6, 7, 1, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.frame)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 4, 0, 1, 1)
        self.line_16 = QtWidgets.QFrame(self.frame)
        self.line_16.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.gridLayout.addWidget(self.line_16, 9, 0, 1, 1)
        self.line_9 = QtWidgets.QFrame(self.frame)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.gridLayout.addWidget(self.line_9, 6, 1, 1, 1)
        self.line_14 = QtWidgets.QFrame(self.frame)
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.gridLayout.addWidget(self.line_14, 8, 3, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.frame)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 2, 3, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ledt_ini_PE = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_ini_PE.setFont(font)
        self.ledt_ini_PE.setObjectName("ledt_ini_PE")
        self.horizontalLayout_4.addWidget(self.ledt_ini_PE)
        self.btn_ini_PE = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ini_PE.sizePolicy().hasHeightForWidth())
        self.btn_ini_PE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ini_PE.setFont(font)
        self.btn_ini_PE.setObjectName("btn_ini_PE")
        self.horizontalLayout_4.addWidget(self.btn_ini_PE)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 1, 1, 1)
        self.lbl_ini_PM = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_ini_PM.setFont(font)
        self.lbl_ini_PM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ini_PM.setObjectName("lbl_ini_PM")
        self.gridLayout.addWidget(self.lbl_ini_PM, 5, 0, 1, 1)
        self.line_20 = QtWidgets.QFrame(self.frame)
        self.line_20.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.gridLayout.addWidget(self.line_20, 0, 0, 1, 1)
        self.line_23 = QtWidgets.QFrame(self.frame)
        self.line_23.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.gridLayout.addWidget(self.line_23, 0, 4, 1, 1)
        self.lbl_ini_PE = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_ini_PE.sizePolicy().hasHeightForWidth())
        self.lbl_ini_PE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_ini_PE.setFont(font)
        self.lbl_ini_PE.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ini_PE.setObjectName("lbl_ini_PE")
        self.gridLayout.addWidget(self.lbl_ini_PE, 3, 0, 1, 1)
        self.line_17 = QtWidgets.QFrame(self.frame)
        self.line_17.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.gridLayout.addWidget(self.line_17, 9, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ledt_ini_PA = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_ini_PA.setFont(font)
        self.ledt_ini_PA.setObjectName("ledt_ini_PA")
        self.horizontalLayout.addWidget(self.ledt_ini_PA)
        self.btn_ini_PA = QtWidgets.QPushButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ini_PA.sizePolicy().hasHeightForWidth())
        self.btn_ini_PA.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ini_PA.setFont(font)
        self.btn_ini_PA.setAutoDefault(False)
        self.btn_ini_PA.setObjectName("btn_ini_PA")
        self.horizontalLayout.addWidget(self.btn_ini_PA)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.frame)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ledt_ini_PM = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_ini_PM.setFont(font)
        self.ledt_ini_PM.setObjectName("ledt_ini_PM")
        self.horizontalLayout_5.addWidget(self.ledt_ini_PM)
        self.btn_ini_PM = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.btn_ini_PM.setFont(font)
        self.btn_ini_PM.setObjectName("btn_ini_PM")
        self.horizontalLayout_5.addWidget(self.btn_ini_PM)
        self.gridLayout.addLayout(self.horizontalLayout_5, 5, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 5, 2, 1, 1)
        self.line_21 = QtWidgets.QFrame(self.frame)
        self.line_21.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.gridLayout.addWidget(self.line_21, 0, 1, 1, 1)
        self.line_19 = QtWidgets.QFrame(self.frame)
        self.line_19.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.gridLayout.addWidget(self.line_19, 9, 4, 1, 1)
        self.lbl_ini_PG = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_ini_PG.setFont(font)
        self.lbl_ini_PG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_ini_PG.setObjectName("lbl_ini_PG")
        self.gridLayout.addWidget(self.lbl_ini_PG, 7, 0, 1, 1)
        self.line_15 = QtWidgets.QFrame(self.frame)
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.gridLayout.addWidget(self.line_15, 8, 4, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout)
        self.verticalLayout_8.addWidget(self.frame)
        self.btn_dat = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_dat.sizePolicy().hasHeightForWidth())
        self.btn_dat.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_dat.setFont(font)
        self.btn_dat.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_dat.setIcon(icon)
        self.btn_dat.setCheckable(True)
        self.btn_dat.setObjectName("btn_dat")
        self.verticalLayout_8.addWidget(self.btn_dat)
        self.frame_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.btn_dat_PM1_delete = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM1_delete.setFont(font)
        self.btn_dat_PM1_delete.setObjectName("btn_dat_PM1_delete")
        self.gridLayout_4.addWidget(self.btn_dat_PM1_delete, 1, 6, 1, 1)
        self.btn_dat_PM1_add = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM1_add.setFont(font)
        self.btn_dat_PM1_add.setObjectName("btn_dat_PM1_add")
        self.gridLayout_4.addWidget(self.btn_dat_PM1_add, 0, 6, 1, 1)
        self.line_30 = QtWidgets.QFrame(self.frame_2)
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.gridLayout_4.addWidget(self.line_30, 9, 2, 1, 1)
        self.line_26 = QtWidgets.QFrame(self.frame_2)
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.gridLayout_4.addWidget(self.line_26, 2, 2, 1, 1)
        self.cbox_dat_TM2 = QtWidgets.QComboBox(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cbox_dat_TM2.setFont(font)
        self.cbox_dat_TM2.setObjectName("cbox_dat_TM2")
        self.gridLayout_4.addWidget(self.cbox_dat_TM2, 8, 1, 1, 1)
        self.line_35 = QtWidgets.QFrame(self.frame_2)
        self.line_35.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_35.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_35.setObjectName("line_35")
        self.gridLayout_4.addWidget(self.line_35, 3, 6, 1, 1)
        self.list_dat_PM1 = QtWidgets.QListWidget(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_dat_PM1.sizePolicy().hasHeightForWidth())
        self.list_dat_PM1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.list_dat_PM1.setFont(font)
        self.list_dat_PM1.setObjectName("list_dat_PM1")
        self.gridLayout_4.addWidget(self.list_dat_PM1, 0, 4, 3, 1)
        self.lbl_dat_PD = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dat_PD.setFont(font)
        self.lbl_dat_PD.setObjectName("lbl_dat_PD")
        self.gridLayout_4.addWidget(self.lbl_dat_PD, 1, 3, 1, 1)
        self.cbox_dat_TM1 = QtWidgets.QComboBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_dat_TM1.sizePolicy().hasHeightForWidth())
        self.cbox_dat_TM1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cbox_dat_TM1.setFont(font)
        self.cbox_dat_TM1.setObjectName("cbox_dat_TM1")
        self.gridLayout_4.addWidget(self.cbox_dat_TM1, 1, 1, 1, 1)
        self.btn_dat_PM2_add = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM2_add.setFont(font)
        self.btn_dat_PM2_add.setObjectName("btn_dat_PM2_add")
        self.gridLayout_4.addWidget(self.btn_dat_PM2_add, 7, 6, 1, 1)
        self.line_27 = QtWidgets.QFrame(self.frame_2)
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.gridLayout_4.addWidget(self.line_27, 0, 2, 1, 1)
        self.line_29 = QtWidgets.QFrame(self.frame_2)
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.gridLayout_4.addWidget(self.line_29, 8, 2, 1, 1)
        self.btn_dat_PM2_delete = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM2_delete.setFont(font)
        self.btn_dat_PM2_delete.setObjectName("btn_dat_PM2_delete")
        self.gridLayout_4.addWidget(self.btn_dat_PM2_delete, 8, 6, 1, 1)
        self.line_34 = QtWidgets.QFrame(self.frame_2)
        self.line_34.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_34.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_34.setObjectName("line_34")
        self.gridLayout_4.addWidget(self.line_34, 3, 4, 1, 1)
        self.lbl_dat_PM2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dat_PM2.setFont(font)
        self.lbl_dat_PM2.setObjectName("lbl_dat_PM2")
        self.gridLayout_4.addWidget(self.lbl_dat_PM2, 8, 3, 1, 1)
        self.lbl_dat_TM1 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dat_TM1.setFont(font)
        self.lbl_dat_TM1.setObjectName("lbl_dat_TM1")
        self.gridLayout_4.addWidget(self.lbl_dat_TM1, 1, 0, 1, 1)
        self.btn_dat_PM1_clear = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM1_clear.setFont(font)
        self.btn_dat_PM1_clear.setObjectName("btn_dat_PM1_clear")
        self.gridLayout_4.addWidget(self.btn_dat_PM1_clear, 2, 6, 1, 1)
        self.line_32 = QtWidgets.QFrame(self.frame_2)
        self.line_32.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.gridLayout_4.addWidget(self.line_32, 3, 1, 1, 1)
        self.btn_dat_PM2_clear = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_dat_PM2_clear.setFont(font)
        self.btn_dat_PM2_clear.setObjectName("btn_dat_PM2_clear")
        self.gridLayout_4.addWidget(self.btn_dat_PM2_clear, 9, 6, 1, 1)
        self.list_dat_PM2 = QtWidgets.QListWidget(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.list_dat_PM2.setFont(font)
        self.list_dat_PM2.setObjectName("list_dat_PM2")
        self.gridLayout_4.addWidget(self.list_dat_PM2, 7, 4, 3, 1)
        self.line_33 = QtWidgets.QFrame(self.frame_2)
        self.line_33.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_33.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_33.setObjectName("line_33")
        self.gridLayout_4.addWidget(self.line_33, 3, 3, 1, 1)
        self.line_28 = QtWidgets.QFrame(self.frame_2)
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.gridLayout_4.addWidget(self.line_28, 7, 2, 1, 1)
        self.line_25 = QtWidgets.QFrame(self.frame_2)
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.gridLayout_4.addWidget(self.line_25, 1, 2, 1, 1)
        self.lbl_dat_TM2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_dat_TM2.setFont(font)
        self.lbl_dat_TM2.setObjectName("lbl_dat_TM2")
        self.gridLayout_4.addWidget(self.lbl_dat_TM2, 8, 0, 1, 1)
        self.line_31 = QtWidgets.QFrame(self.frame_2)
        self.line_31.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.gridLayout_4.addWidget(self.line_31, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 2, 7, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_2)
        self.btn_idr = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_idr.sizePolicy().hasHeightForWidth())
        self.btn_idr.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_idr.setFont(font)
        self.btn_idr.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_idr.setIcon(icon)
        self.btn_idr.setCheckable(True)
        self.btn_idr.setObjectName("btn_idr")
        self.verticalLayout_8.addWidget(self.btn_idr)
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lbl_idr_PIR = QtWidgets.QLabel(self.frame_4)
        self.lbl_idr_PIR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_idr_PIR.setObjectName("lbl_idr_PIR")
        self.gridLayout_6.addWidget(self.lbl_idr_PIR, 11, 0, 1, 1)
        self.lbl_idr_TF = QtWidgets.QLabel(self.frame_4)
        self.lbl_idr_TF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_idr_TF.setObjectName("lbl_idr_TF")
        self.gridLayout_6.addWidget(self.lbl_idr_TF, 12, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_idr_PIR_add = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_idr_PIR_add.sizePolicy().hasHeightForWidth())
        self.btn_idr_PIR_add.setSizePolicy(sizePolicy)
        self.btn_idr_PIR_add.setObjectName("btn_idr_PIR_add")
        self.verticalLayout_2.addWidget(self.btn_idr_PIR_add)
        self.btn_idr_PIR_delete = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_idr_PIR_delete.sizePolicy().hasHeightForWidth())
        self.btn_idr_PIR_delete.setSizePolicy(sizePolicy)
        self.btn_idr_PIR_delete.setObjectName("btn_idr_PIR_delete")
        self.verticalLayout_2.addWidget(self.btn_idr_PIR_delete)
        self.btn_idr_PIR_clear = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_idr_PIR_clear.sizePolicy().hasHeightForWidth())
        self.btn_idr_PIR_clear.setSizePolicy(sizePolicy)
        self.btn_idr_PIR_clear.setObjectName("btn_idr_PIR_clear")
        self.verticalLayout_2.addWidget(self.btn_idr_PIR_clear)
        self.gridLayout_6.addLayout(self.verticalLayout_2, 11, 2, 1, 1)
        self.cbox_idr_TIR = QtWidgets.QComboBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_idr_TIR.sizePolicy().hasHeightForWidth())
        self.cbox_idr_TIR.setSizePolicy(sizePolicy)
        self.cbox_idr_TIR.setObjectName("cbox_idr_TIR")
        self.gridLayout_6.addWidget(self.cbox_idr_TIR, 4, 1, 1, 1)
        self.list_idr_PIR = QtWidgets.QListWidget(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_idr_PIR.sizePolicy().hasHeightForWidth())
        self.list_idr_PIR.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.list_idr_PIR.setFont(font)
        self.list_idr_PIR.setObjectName("list_idr_PIR")
        self.gridLayout_6.addWidget(self.list_idr_PIR, 11, 1, 1, 1)
        self.lbl_idr_TIR = QtWidgets.QLabel(self.frame_4)
        self.lbl_idr_TIR.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_idr_TIR.setObjectName("lbl_idr_TIR")
        self.gridLayout_6.addWidget(self.lbl_idr_TIR, 4, 0, 1, 1)
        self.sbox_idr_TF = QtWidgets.QDoubleSpinBox(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_idr_TF.sizePolicy().hasHeightForWidth())
        self.sbox_idr_TF.setSizePolicy(sizePolicy)
        self.sbox_idr_TF.setDecimals(3)
        self.sbox_idr_TF.setMinimum(0.0)
        self.sbox_idr_TF.setMaximum(100000.0)
        self.sbox_idr_TF.setProperty("value", 0.0)
        self.sbox_idr_TF.setObjectName("sbox_idr_TF")
        self.gridLayout_6.addWidget(self.sbox_idr_TF, 12, 1, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_4)
        self.btn_qua = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_qua.sizePolicy().hasHeightForWidth())
        self.btn_qua.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_qua.setFont(font)
        self.btn_qua.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.btn_qua.setIcon(icon)
        self.btn_qua.setCheckable(True)
        self.btn_qua.setObjectName("btn_qua")
        self.verticalLayout_8.addWidget(self.btn_qua)
        self.frame_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.lbl_qua_DLM = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_DLM.sizePolicy().hasHeightForWidth())
        self.lbl_qua_DLM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DLM.setFont(font)
        self.lbl_qua_DLM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_DLM.setObjectName("lbl_qua_DLM")
        self.gridLayout_7.addWidget(self.lbl_qua_DLM, 13, 0, 1, 1)
        self.lbl_qua_TQ = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_TQ.sizePolicy().hasHeightForWidth())
        self.lbl_qua_TQ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_TQ.setFont(font)
        self.lbl_qua_TQ.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_TQ.setObjectName("lbl_qua_TQ")
        self.gridLayout_7.addWidget(self.lbl_qua_TQ, 0, 0, 1, 1)
        self.lbl_qua_DFP = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_DFP.sizePolicy().hasHeightForWidth())
        self.lbl_qua_DFP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DFP.setFont(font)
        self.lbl_qua_DFP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_DFP.setObjectName("lbl_qua_DFP")
        self.gridLayout_7.addWidget(self.lbl_qua_DFP, 20, 0, 1, 1)
        self.lbl_qua_DLP = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_DLP.sizePolicy().hasHeightForWidth())
        self.lbl_qua_DLP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DLP.setFont(font)
        self.lbl_qua_DLP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_DLP.setObjectName("lbl_qua_DLP")
        self.gridLayout_7.addWidget(self.lbl_qua_DLP, 14, 0, 1, 1)
        self.sbox_qua_DFRHWIM = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_qua_DFRHWIM.sizePolicy().hasHeightForWidth())
        self.sbox_qua_DFRHWIM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbox_qua_DFRHWIM.setFont(font)
        self.sbox_qua_DFRHWIM.setMinimum(0.0)
        self.sbox_qua_DFRHWIM.setMaximum(100000.0)
        self.sbox_qua_DFRHWIM.setProperty("value", 0.0)
        self.sbox_qua_DFRHWIM.setObjectName("sbox_qua_DFRHWIM")
        self.gridLayout_7.addWidget(self.sbox_qua_DFRHWIM, 19, 3, 1, 1)
        self.lbl_qua_DLI = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_DLI.sizePolicy().hasHeightForWidth())
        self.lbl_qua_DLI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DLI.setFont(font)
        self.lbl_qua_DLI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_DLI.setObjectName("lbl_qua_DLI")
        self.gridLayout_7.addWidget(self.lbl_qua_DLI, 15, 0, 1, 1)
        self.sbox_qua_DLPHWAP = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_qua_DLPHWAP.sizePolicy().hasHeightForWidth())
        self.sbox_qua_DLPHWAP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbox_qua_DLPHWAP.setFont(font)
        self.sbox_qua_DLPHWAP.setMinimum(0.0)
        self.sbox_qua_DLPHWAP.setMaximum(100000.0)
        self.sbox_qua_DLPHWAP.setProperty("value", 0.0)
        self.sbox_qua_DLPHWAP.setObjectName("sbox_qua_DLPHWAP")
        self.gridLayout_7.addWidget(self.sbox_qua_DLPHWAP, 14, 3, 1, 1)
        self.sbox_qua_DFPHWAP = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_qua_DFPHWAP.sizePolicy().hasHeightForWidth())
        self.sbox_qua_DFPHWAP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbox_qua_DFPHWAP.setFont(font)
        self.sbox_qua_DFPHWAP.setMinimum(0.0)
        self.sbox_qua_DFPHWAP.setMaximum(100000.0)
        self.sbox_qua_DFPHWAP.setProperty("value", 0.0)
        self.sbox_qua_DFPHWAP.setObjectName("sbox_qua_DFPHWAP")
        self.gridLayout_7.addWidget(self.sbox_qua_DFPHWAP, 20, 3, 1, 1)
        self.sbox_qua_DLRHWIM = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_qua_DLRHWIM.sizePolicy().hasHeightForWidth())
        self.sbox_qua_DLRHWIM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbox_qua_DLRHWIM.setFont(font)
        self.sbox_qua_DLRHWIM.setMinimum(0.0)
        self.sbox_qua_DLRHWIM.setMaximum(100000.0)
        self.sbox_qua_DLRHWIM.setProperty("value", 0.0)
        self.sbox_qua_DLRHWIM.setObjectName("sbox_qua_DLRHWIM")
        self.gridLayout_7.addWidget(self.sbox_qua_DLRHWIM, 13, 3, 1, 1)
        self.lbl_qua_DFM = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_DFM.sizePolicy().hasHeightForWidth())
        self.lbl_qua_DFM.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DFM.setFont(font)
        self.lbl_qua_DFM.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_DFM.setObjectName("lbl_qua_DFM")
        self.gridLayout_7.addWidget(self.lbl_qua_DFM, 19, 0, 1, 1)
        self.lbl_qua_RMRI = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_RMRI.sizePolicy().hasHeightForWidth())
        self.lbl_qua_RMRI.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_RMRI.setFont(font)
        self.lbl_qua_RMRI.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_RMRI.setObjectName("lbl_qua_RMRI")
        self.gridLayout_7.addWidget(self.lbl_qua_RMRI, 10, 0, 1, 1)
        self.lbl_qua_DFC = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_DFC.setFont(font)
        self.lbl_qua_DFC.setObjectName("lbl_qua_DFC")
        self.gridLayout_7.addWidget(self.lbl_qua_DFC, 16, 0, 1, 1)
        self.lbl_qua_RPHWAP = QtWidgets.QLabel(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_qua_RPHWAP.sizePolicy().hasHeightForWidth())
        self.lbl_qua_RPHWAP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_qua_RPHWAP.setFont(font)
        self.lbl_qua_RPHWAP.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_qua_RPHWAP.setObjectName("lbl_qua_RPHWAP")
        self.gridLayout_7.addWidget(self.lbl_qua_RPHWAP, 1, 0, 1, 1)
        self.ledt_qua_RMRI = QtWidgets.QLineEdit(self.frame_3)
        self.ledt_qua_RMRI.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ledt_qua_RMRI.sizePolicy().hasHeightForWidth())
        self.ledt_qua_RMRI.setSizePolicy(sizePolicy)
        self.ledt_qua_RMRI.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_qua_RMRI.setFont(font)
        self.ledt_qua_RMRI.setObjectName("ledt_qua_RMRI")
        self.gridLayout_7.addWidget(self.ledt_qua_RMRI, 10, 3, 1, 1)
        self.sbox_qua_RPHWAP = QtWidgets.QDoubleSpinBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sbox_qua_RPHWAP.sizePolicy().hasHeightForWidth())
        self.sbox_qua_RPHWAP.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.sbox_qua_RPHWAP.setFont(font)
        self.sbox_qua_RPHWAP.setMinimum(0.0)
        self.sbox_qua_RPHWAP.setMaximum(100000.0)
        self.sbox_qua_RPHWAP.setProperty("value", 0.0)
        self.sbox_qua_RPHWAP.setObjectName("sbox_qua_RPHWAP")
        self.gridLayout_7.addWidget(self.sbox_qua_RPHWAP, 1, 3, 1, 1)
        self.cbox_qua_DFC = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_qua_DFC.sizePolicy().hasHeightForWidth())
        self.cbox_qua_DFC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cbox_qua_DFC.setFont(font)
        self.cbox_qua_DFC.setObjectName("cbox_qua_DFC")
        self.gridLayout_7.addWidget(self.cbox_qua_DFC, 16, 3, 1, 1)
        self.cbox_qua_TQ = QtWidgets.QComboBox(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_qua_TQ.sizePolicy().hasHeightForWidth())
        self.cbox_qua_TQ.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.cbox_qua_TQ.setFont(font)
        self.cbox_qua_TQ.setObjectName("cbox_qua_TQ")
        self.gridLayout_7.addWidget(self.cbox_qua_TQ, 0, 3, 1, 1)
        self.ledt_qua_DLLI = QtWidgets.QLineEdit(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.ledt_qua_DLLI.setFont(font)
        self.ledt_qua_DLLI.setObjectName("ledt_qua_DLLI")
        self.gridLayout_7.addWidget(self.ledt_qua_DLLI, 15, 3, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 3, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_3)
        self.pushButton = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon_show.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(":/icons/icon_hide.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton.setIcon(icon1)
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_8.addWidget(self.pushButton)
        self.frame_5 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.ledt_exp_PE = QtWidgets.QLineEdit(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.ledt_exp_PE.setFont(font)
        self.ledt_exp_PE.setObjectName("ledt_exp_PE")
        self.gridLayout_9.addWidget(self.ledt_exp_PE, 1, 1, 1, 1)
        self.cbox_exp_TE = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_exp_TE.sizePolicy().hasHeightForWidth())
        self.cbox_exp_TE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbox_exp_TE.setFont(font)
        self.cbox_exp_TE.setObjectName("cbox_exp_TE")
        self.gridLayout_9.addWidget(self.cbox_exp_TE, 2, 1, 1, 1)
        self.lbl_exp_FCNF = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_exp_FCNF.sizePolicy().hasHeightForWidth())
        self.lbl_exp_FCNF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_exp_FCNF.setFont(font)
        self.lbl_exp_FCNF.setObjectName("lbl_exp_FCNF")
        self.gridLayout_9.addWidget(self.lbl_exp_FCNF, 3, 0, 1, 1)
        self.lbl_exp_PE = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_exp_PE.setFont(font)
        self.lbl_exp_PE.setObjectName("lbl_exp_PE")
        self.gridLayout_9.addWidget(self.lbl_exp_PE, 1, 0, 1, 1)
        self.btn_exp_PE = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_exp_PE.sizePolicy().hasHeightForWidth())
        self.btn_exp_PE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btn_exp_PE.setFont(font)
        self.btn_exp_PE.setObjectName("btn_exp_PE")
        self.gridLayout_9.addWidget(self.btn_exp_PE, 1, 4, 1, 1)
        self.lbl_exp_TE = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_exp_TE.setFont(font)
        self.lbl_exp_TE.setObjectName("lbl_exp_TE")
        self.gridLayout_9.addWidget(self.lbl_exp_TE, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem5, 1, 5, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cbox_exp_FCNF = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_exp_FCNF.sizePolicy().hasHeightForWidth())
        self.cbox_exp_FCNF.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbox_exp_FCNF.setFont(font)
        self.cbox_exp_FCNF.setObjectName("cbox_exp_FCNF")
        self.horizontalLayout_2.addWidget(self.cbox_exp_FCNF)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem6)
        self.lbl_exp_FEE = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_exp_FEE.sizePolicy().hasHeightForWidth())
        self.lbl_exp_FEE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.lbl_exp_FEE.setFont(font)
        self.lbl_exp_FEE.setObjectName("lbl_exp_FEE")
        self.horizontalLayout_2.addWidget(self.lbl_exp_FEE)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 3, 1, 1, 1)
        self.cbox_exp_FEE = QtWidgets.QComboBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbox_exp_FEE.sizePolicy().hasHeightForWidth())
        self.cbox_exp_FEE.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cbox_exp_FEE.setFont(font)
        self.cbox_exp_FEE.setObjectName("cbox_exp_FEE")
        self.gridLayout_9.addWidget(self.cbox_exp_FEE, 3, 4, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.frame_5)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.tab_box.addTab(self.tab_Quantitation, "")
        self.tab_Summary = QtWidgets.QWidget()
        self.tab_Summary.setObjectName("tab_Summary")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_Summary)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_Summary)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 928, 817))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_summary_If = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_If.sizePolicy().hasHeightForWidth())
        self.btn_summary_If.setSizePolicy(sizePolicy)
        self.btn_summary_If.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_If.setFont(font)
        self.btn_summary_If.setToolTip("")
        self.btn_summary_If.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_If.setIcon(icon1)
        self.btn_summary_If.setCheckable(True)
        self.btn_summary_If.setFlat(False)
        self.btn_summary_If.setObjectName("btn_summary_If")
        self.verticalLayout_4.addWidget(self.btn_summary_If)
        self.frame_6 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tbl_If = QtWidgets.QTableWidget(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_If.sizePolicy().hasHeightForWidth())
        self.tbl_If.setSizePolicy(sizePolicy)
        self.tbl_If.setToolTip("")
        self.tbl_If.setToolTipDuration(-1)
        self.tbl_If.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_If.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tbl_If.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tbl_If.setMidLineWidth(0)
        self.tbl_If.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tbl_If.setAutoScroll(True)
        self.tbl_If.setAutoScrollMargin(16)
        self.tbl_If.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_If.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.tbl_If.setAlternatingRowColors(False)
        self.tbl_If.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_If.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_If.setWordWrap(True)
        self.tbl_If.setCornerButtonEnabled(True)
        self.tbl_If.setObjectName("tbl_If")
        self.tbl_If.setColumnCount(2)
        self.tbl_If.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_If.setItem(3, 1, item)
        self.tbl_If.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_If.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_If.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_If.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_If.horizontalHeader().setStretchLastSection(True)
        self.tbl_If.verticalHeader().setVisible(False)
        self.tbl_If.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_If.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_5.addWidget(self.tbl_If)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.btn__summary_D = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn__summary_D.sizePolicy().hasHeightForWidth())
        self.btn__summary_D.setSizePolicy(sizePolicy)
        self.btn__summary_D.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn__summary_D.setFont(font)
        self.btn__summary_D.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn__summary_D.setIcon(icon1)
        self.btn__summary_D.setCheckable(True)
        self.btn__summary_D.setFlat(False)
        self.btn__summary_D.setObjectName("btn__summary_D")
        self.verticalLayout_4.addWidget(self.btn__summary_D)
        self.frame_7 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.tbl_D = QtWidgets.QTableWidget(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_D.sizePolicy().hasHeightForWidth())
        self.tbl_D.setSizePolicy(sizePolicy)
        self.tbl_D.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_D.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_D.setAlternatingRowColors(False)
        self.tbl_D.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_D.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_D.setWordWrap(True)
        self.tbl_D.setCornerButtonEnabled(True)
        self.tbl_D.setObjectName("tbl_D")
        self.tbl_D.setColumnCount(2)
        self.tbl_D.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_D.setItem(3, 1, item)
        self.tbl_D.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_D.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_D.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_D.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_D.horizontalHeader().setStretchLastSection(True)
        self.tbl_D.verticalHeader().setVisible(False)
        self.tbl_D.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_D.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_6.addWidget(self.tbl_D)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.btn_summary_IR = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_IR.sizePolicy().hasHeightForWidth())
        self.btn_summary_IR.setSizePolicy(sizePolicy)
        self.btn_summary_IR.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_IR.setFont(font)
        self.btn_summary_IR.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_IR.setIcon(icon1)
        self.btn_summary_IR.setCheckable(True)
        self.btn_summary_IR.setFlat(False)
        self.btn_summary_IR.setObjectName("btn_summary_IR")
        self.verticalLayout_4.addWidget(self.btn_summary_IR)
        self.frame_8 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.tbl_IR = QtWidgets.QTableWidget(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_IR.sizePolicy().hasHeightForWidth())
        self.tbl_IR.setSizePolicy(sizePolicy)
        self.tbl_IR.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_IR.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_IR.setAlternatingRowColors(False)
        self.tbl_IR.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_IR.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_IR.setWordWrap(True)
        self.tbl_IR.setCornerButtonEnabled(True)
        self.tbl_IR.setObjectName("tbl_IR")
        self.tbl_IR.setColumnCount(2)
        self.tbl_IR.setRowCount(3)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_IR.setItem(2, 1, item)
        self.tbl_IR.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_IR.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_IR.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_IR.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_IR.horizontalHeader().setStretchLastSection(True)
        self.tbl_IR.verticalHeader().setVisible(False)
        self.tbl_IR.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_IR.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_7.addWidget(self.tbl_IR)
        self.verticalLayout_4.addWidget(self.frame_8)
        self.btn_summary_Q = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_summary_Q.sizePolicy().hasHeightForWidth())
        self.btn_summary_Q.setSizePolicy(sizePolicy)
        self.btn_summary_Q.setMinimumSize(QtCore.QSize(0, 18))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.btn_summary_Q.setFont(font)
        self.btn_summary_Q.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_Q.setIcon(icon1)
        self.btn_summary_Q.setCheckable(True)
        self.btn_summary_Q.setFlat(False)
        self.btn_summary_Q.setObjectName("btn_summary_Q")
        self.verticalLayout_4.addWidget(self.btn_summary_Q)
        self.frame_9 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.tbl_Q = QtWidgets.QTableWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_Q.sizePolicy().hasHeightForWidth())
        self.tbl_Q.setSizePolicy(sizePolicy)
        self.tbl_Q.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_Q.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_Q.setAlternatingRowColors(False)
        self.tbl_Q.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_Q.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_Q.setWordWrap(True)
        self.tbl_Q.setCornerButtonEnabled(True)
        self.tbl_Q.setObjectName("tbl_Q")
        self.tbl_Q.setColumnCount(2)
        self.tbl_Q.setRowCount(9)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(6, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(7, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_Q.setItem(8, 1, item)
        self.tbl_Q.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_Q.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_Q.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_Q.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_Q.horizontalHeader().setStretchLastSection(True)
        self.tbl_Q.verticalHeader().setVisible(False)
        self.tbl_Q.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_Q.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_10.addWidget(self.tbl_Q)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.btn_summary_E = QtWidgets.QPushButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_summary_E.setFont(font)
        self.btn_summary_E.setStyleSheet("QPushButton{text-align:left; border:none;margin-bottom:2px;}")
        self.btn_summary_E.setIcon(icon1)
        self.btn_summary_E.setCheckable(True)
        self.btn_summary_E.setObjectName("btn_summary_E")
        self.verticalLayout_4.addWidget(self.btn_summary_E)
        self.frame_10 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.tbl_E = QtWidgets.QTableWidget(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_E.sizePolicy().hasHeightForWidth())
        self.tbl_E.setSizePolicy(sizePolicy)
        self.tbl_E.setStyleSheet("QTableWidget{margin-left:20px;}")
        self.tbl_E.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tbl_E.setAlternatingRowColors(False)
        self.tbl_E.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tbl_E.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tbl_E.setWordWrap(True)
        self.tbl_E.setCornerButtonEnabled(True)
        self.tbl_E.setObjectName("tbl_E")
        self.tbl_E.setColumnCount(2)
        self.tbl_E.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_E.setItem(3, 0, item)
        self.tbl_E.horizontalHeader().setCascadingSectionResizes(True)
        self.tbl_E.horizontalHeader().setDefaultSectionSize(150)
        self.tbl_E.horizontalHeader().setMinimumSectionSize(50)
        self.tbl_E.horizontalHeader().setSortIndicatorShown(False)
        self.tbl_E.horizontalHeader().setStretchLastSection(True)
        self.tbl_E.verticalHeader().setVisible(False)
        self.tbl_E.verticalHeader().setCascadingSectionResizes(False)
        self.tbl_E.verticalHeader().setDefaultSectionSize(32)
        self.verticalLayout_11.addWidget(self.tbl_E)
        self.verticalLayout_4.addWidget(self.frame_10)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea_2)
        self.tab_box.addTab(self.tab_Summary, "")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.tab_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 997, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tab_box.setCurrentIndex(0)
        self.btn_qua.toggled['bool'].connect(self.frame_3.setHidden)
        self.btn_ini.toggled['bool'].connect(self.frame.setHidden)
        self.btn_dat.toggled['bool'].connect(self.frame_2.setHidden)
        self.btn_idr.toggled['bool'].connect(self.frame_4.setHidden)
        self.pushButton.toggled['bool'].connect(self.frame_5.setHidden)
        self.btn_summary_If.toggled['bool'].connect(self.frame_6.setHidden)
        self.btn__summary_D.toggled['bool'].connect(self.frame_7.setHidden)
        self.btn_summary_IR.toggled['bool'].connect(self.frame_8.setHidden)
        self.btn_summary_Q.toggled['bool'].connect(self.frame_9.setHidden)
        self.btn_summary_E.toggled['bool'].connect(self.frame_10.setHidden)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_run.setText(_translate("MainWindow", "run"))
        self.btn_import.setText(_translate("MainWindow", "import"))
        self.btn_save_as.setText(_translate("MainWindow", "save as"))
        self.btn_save.setText(_translate("MainWindow", "save"))
        self.btn_ini.setText(_translate("MainWindow", "Ini files"))
        self.lbl_ini_PA.setToolTip(_translate("MainWindow", "<html><head/><body><p>to_be_continued...</p></body></html>"))
        self.lbl_ini_PA.setText(_translate("MainWindow", "PATH_AA"))
        self.btn_ini_PG.setText(_translate("MainWindow", "Browser"))
        self.btn_ini_PE.setText(_translate("MainWindow", "Browser"))
        self.lbl_ini_PM.setText(_translate("MainWindow", "PATH_MOD"))
        self.lbl_ini_PE.setText(_translate("MainWindow", "PATH_ELEMENT"))
        self.btn_ini_PA.setText(_translate("MainWindow", "Browser"))
        self.btn_ini_PM.setText(_translate("MainWindow", "Browser"))
        self.lbl_ini_PG.setText(_translate("MainWindow", "PATH_GLYCO"))
        self.btn_dat.setText(_translate("MainWindow", "Data"))
        self.btn_dat_PM1_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_dat_PM1_add.setText(_translate("MainWindow", "Add"))
        self.lbl_dat_PD.setText(_translate("MainWindow", "PATH_MS1"))
        self.btn_dat_PM2_add.setText(_translate("MainWindow", "Add"))
        self.btn_dat_PM2_delete.setText(_translate("MainWindow", "Delete"))
        self.lbl_dat_PM2.setText(_translate("MainWindow", "PATH_MS2"))
        self.lbl_dat_TM1.setText(_translate("MainWindow", "TYPE_MS1"))
        self.btn_dat_PM1_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_dat_PM2_clear.setText(_translate("MainWindow", "Clear"))
        self.lbl_dat_TM2.setText(_translate("MainWindow", "TYPE_MS2"))
        self.btn_idr.setText(_translate("MainWindow", "Identification Result"))
        self.lbl_idr_PIR.setText(_translate("MainWindow", "PATH_IDENTIFICATION_RESULT"))
        self.lbl_idr_TF.setText(_translate("MainWindow", "THRESHOLD_FDR"))
        self.btn_idr_PIR_add.setText(_translate("MainWindow", "Add"))
        self.btn_idr_PIR_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_idr_PIR_clear.setText(_translate("MainWindow", "Clear"))
        self.lbl_idr_TIR.setText(_translate("MainWindow", "TYPE_IDENTIFICATION_RESULT"))
        self.btn_qua.setText(_translate("MainWindow", "Quantitation"))
        self.lbl_qua_DLM.setText(_translate("MainWindow", "DDALL_RT_HALF_WIN_IN_MIN"))
        self.lbl_qua_TQ.setText(_translate("MainWindow", "TYPE_QUANT"))
        self.lbl_qua_DFP.setText(_translate("MainWindow", "DDALF_PPM_HALF_WIN_ACCURACY_PEAK"))
        self.lbl_qua_DLP.setText(_translate("MainWindow", "DDALL_PPM_HALF_WIN_ACCURACY_PEAK"))
        self.lbl_qua_DLI.setText(_translate("MainWindow", "DDALL_LABEL_INFO"))
        self.lbl_qua_DFM.setText(_translate("MainWindow", "DDALF_RT_HALF_WIN_IN_MIN"))
        self.lbl_qua_RMRI.setText(_translate("MainWindow", "RI_MASS_REPORT_ION"))
        self.lbl_qua_DFC.setText(_translate("MainWindow", "DDALL_FLAG_CALIBRATION_18O"))
        self.lbl_qua_RPHWAP.setText(_translate("MainWindow", "RI_PPM_HALF_WIN_ACCURACY_PEAK"))
        self.pushButton.setText(_translate("MainWindow", "Export"))
        self.lbl_exp_FCNF.setText(_translate("MainWindow", "FLAG_CREATE_NEW_FOLDER"))
        self.lbl_exp_PE.setText(_translate("MainWindow", "PATH_EXPORT"))
        self.btn_exp_PE.setText(_translate("MainWindow", "Browser"))
        self.lbl_exp_TE.setText(_translate("MainWindow", "TYPE_EXPORT"))
        self.lbl_exp_FEE.setText(_translate("MainWindow", "FLAG_EXPORT_EVIDENCE"))
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_Quantitation), _translate("MainWindow", "Quantitation"))
        self.btn_summary_If.setText(_translate("MainWindow", "Ini files"))
        item = self.tbl_If.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbl_If.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tbl_If.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tbl_If.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tbl_If.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.tbl_If.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tbl_If.isSortingEnabled()
        self.tbl_If.setSortingEnabled(False)
        item = self.tbl_If.item(0, 0)
        item.setText(_translate("MainWindow", "PATH_AA"))
        item = self.tbl_If.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_If.item(1, 0)
        item.setText(_translate("MainWindow", "PATH_ELEMENT"))
        item = self.tbl_If.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_If.item(2, 0)
        item.setText(_translate("MainWindow", "PATH_MOD"))
        item = self.tbl_If.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_If.item(3, 0)
        item.setText(_translate("MainWindow", "PATH_GLYCO"))
        item = self.tbl_If.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        self.tbl_If.setSortingEnabled(__sortingEnabled)
        self.btn__summary_D.setText(_translate("MainWindow", "Data"))
        item = self.tbl_D.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbl_D.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tbl_D.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tbl_D.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tbl_D.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.tbl_D.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tbl_D.isSortingEnabled()
        self.tbl_D.setSortingEnabled(False)
        item = self.tbl_D.item(0, 0)
        item.setText(_translate("MainWindow", "TYPE_MS1"))
        item = self.tbl_D.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_D.item(1, 0)
        item.setText(_translate("MainWindow", "PATH_MS1"))
        item = self.tbl_D.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_D.item(2, 0)
        item.setText(_translate("MainWindow", "TYPE_MS2"))
        item = self.tbl_D.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_D.item(3, 0)
        item.setText(_translate("MainWindow", "PATH_MS2"))
        item = self.tbl_D.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        self.tbl_D.setSortingEnabled(__sortingEnabled)
        self.btn_summary_IR.setText(_translate("MainWindow", "Identification Result"))
        item = self.tbl_IR.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbl_IR.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tbl_IR.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tbl_IR.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.tbl_IR.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tbl_IR.isSortingEnabled()
        self.tbl_IR.setSortingEnabled(False)
        item = self.tbl_IR.item(0, 0)
        item.setText(_translate("MainWindow", "TYPE_IDENTIFICATION_RESULT"))
        item = self.tbl_IR.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_IR.item(1, 0)
        item.setText(_translate("MainWindow", "PATH_IDENTIFICATION_RESULT"))
        item = self.tbl_IR.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_IR.item(2, 0)
        item.setText(_translate("MainWindow", "THRESHOLD_FDR"))
        item = self.tbl_IR.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        self.tbl_IR.setSortingEnabled(__sortingEnabled)
        self.btn_summary_Q.setText(_translate("MainWindow", "Quantitation"))
        item = self.tbl_Q.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbl_Q.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tbl_Q.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2"))
        item = self.tbl_Q.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "3"))
        item = self.tbl_Q.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "4"))
        item = self.tbl_Q.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "5"))
        item = self.tbl_Q.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "6"))
        item = self.tbl_Q.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "7"))
        item = self.tbl_Q.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tbl_Q.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.tbl_Q.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tbl_Q.isSortingEnabled()
        self.tbl_Q.setSortingEnabled(False)
        item = self.tbl_Q.item(0, 0)
        item.setText(_translate("MainWindow", "TYPE_QUANT"))
        item = self.tbl_Q.item(0, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(1, 0)
        item.setText(_translate("MainWindow", "RI_PPM_HALF_WIN_ACCURACY_PEAK"))
        item = self.tbl_Q.item(1, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(2, 0)
        item.setText(_translate("MainWindow", "RI_MASS_REPORT_ION"))
        item = self.tbl_Q.item(2, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(3, 0)
        item.setText(_translate("MainWindow", "DDALL_RT_HALF_WIN_IN_MIN"))
        item = self.tbl_Q.item(3, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(4, 0)
        item.setText(_translate("MainWindow", "DDALL_PPM_HALF_WIN_ACCURACY_PEAK"))
        item = self.tbl_Q.item(4, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(5, 0)
        item.setText(_translate("MainWindow", "DDALL_LABEL_INFO"))
        item = self.tbl_Q.item(5, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(6, 0)
        item.setText(_translate("MainWindow", "DDALL_FLAG_CALIBRATION_18O"))
        item = self.tbl_Q.item(6, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(7, 0)
        item.setText(_translate("MainWindow", "DDALF_RT_HALF_WIN_IN_MIN"))
        item = self.tbl_Q.item(7, 1)
        item.setText(_translate("MainWindow", "-"))
        item = self.tbl_Q.item(8, 0)
        item.setText(_translate("MainWindow", "DDALF_PPM_HALF_WIN_ACCURACY_PEAK"))
        item = self.tbl_Q.item(8, 1)
        item.setText(_translate("MainWindow", "-"))
        self.tbl_Q.setSortingEnabled(__sortingEnabled)
        self.btn_summary_E.setText(_translate("MainWindow", "Export"))
        item = self.tbl_E.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tbl_E.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "1"))
        item = self.tbl_E.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tbl_E.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tbl_E.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Property"))
        item = self.tbl_E.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        __sortingEnabled = self.tbl_E.isSortingEnabled()
        self.tbl_E.setSortingEnabled(False)
        item = self.tbl_E.item(0, 0)
        item.setText(_translate("MainWindow", "PATH_EXPORT"))
        item = self.tbl_E.item(1, 0)
        item.setText(_translate("MainWindow", "TYPE_EXPORT"))
        item = self.tbl_E.item(2, 0)
        item.setText(_translate("MainWindow", "FLAG_CREATE_NEW_FOLDER"))
        item = self.tbl_E.item(3, 0)
        item.setText(_translate("MainWindow", "FLAG_EXPORT_EVIDENCE"))
        self.tbl_E.setSortingEnabled(__sortingEnabled)
        self.tab_box.setTabText(self.tab_box.indexOf(self.tab_Summary), _translate("MainWindow", "Summary"))
